<?php

namespace Database\Seeders;

use App\Models\Card;
use Illuminate\Database\Seeder;

class CardSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cards = [
            [
                'title' => 'Pedido de Certidões',
                'label' => 'Registro Civil de Pessoas Naturais',
                'description' => 'Solicite certidões e documentos do Registro Civil com praticidade e segurança.',
                'icon_url' => 'https://www.figma.com/api/mcp/asset/d0f50ac4-182b-48a0-9c00-7225cb762241.png',
                'href' => 'https://www.rtdbrasil.org.br/',
                'accent' => 'border-brand-green',
                'tag_text' => 'text-brand-green',
                'tag_bg' => 'bg-[#f7fbf4]',
                'category' => 'registro_civil',
                'category_label' => 'Registro Civil de Pessoas Naturais',
                'sort_order' => 1,
                'show_in_quick_access' => true,
                'show_in_service_grid' => false,
                'is_active' => true,
            ],
            [
                'title' => 'Acompanhamento Registral',
                'label' => 'Registro de Imóveis',
                'description' => 'Acompanhe atos e informações registradas diretamente no sistema imobiliário.',
                'icon_url' => 'https://www.figma.com/api/mcp/asset/7187cb99-bbc3-488a-af5a-25a4eb969c20.png',
                'href' => 'https://registradores.onr.org.br/servicos/actitulo/frmAcompanhamentoTitulo.aspx',
                'accent' => 'border-brand-orange',
                'tag_text' => 'text-brand-orange',
                'tag_bg' => 'bg-[#fff8f3]',
                'category' => 'registro_imoveis',
                'category_label' => 'Registro de Imóveis',
                'sort_order' => 2,
                'show_in_quick_access' => true,
                'show_in_service_grid' => false,
                'is_active' => true,
            ],
            [
                'title' => 'Assinatura Eletrônica de Documentos',
                'label' => 'Pessoa Jurídica, Títulos e documentos',
                'description' => 'Assine documentos de forma eletrônica com validade jurídica reconhecida.',
                'icon_url' => 'https://www.figma.com/api/mcp/asset/973c87d4-0fa5-4583-a13c-19dd9c710364.png',
                'href' => 'https://www.rtdbrasil.org.br/coletaassinatura/assinardocumento',
                'accent' => 'border-brand-purple',
                'tag_text' => 'text-brand-purple',
                'tag_bg' => 'bg-[#f7f5ff]',
                'category' => 'titulos_documentos',
                'category_label' => 'Registro de Títulos e Documentos',
                'sort_order' => 3,
                'show_in_quick_access' => true,
                'show_in_service_grid' => false,
                'is_active' => true,
            ],
            [
                'title' => 'Certificado Digital Notarizado',
                'label' => 'Tabelionato de Notas',
                'description' => 'Emita e valide certificados digitais para uso jurídico e burocrático.',
                'icon_url' => 'https://www.figma.com/api/mcp/asset/ab40a91d-80b8-450d-bc75-2933aa830784.png',
                'href' => 'https://www.e-notariado.org.br/customer/certificate-request',
                'accent' => 'border-brand-teal',
                'tag_text' => 'text-brand-teal',
                'tag_bg' => 'bg-[#f2fcfd]',
                'category' => 'tabelionato_notas',
                'category_label' => 'Tabelionato de Notas',
                'sort_order' => 4,
                'show_in_quick_access' => true,
                'show_in_service_grid' => false,
                'is_active' => true,
            ],
            [
                'title' => 'Consulta de CPF/CNPJ',
                'label' => 'Tabelionato de Protesto',
                'description' => 'Consulte e acompanhe documentos e pendências no Tabelionato de Protesto.',
                'icon_url' => 'https://www.figma.com/api/mcp/asset/1ee44ae4-3ac1-41f7-8755-0634bde282c9.png',
                'href' => 'https://www.pesquisaprotesto.com.br/servico/consulta-documento',
                'accent' => 'border-brand-blue',
                'tag_text' => 'text-brand-blue',
                'tag_bg' => 'bg-[#f3f9ff]',
                'category' => 'tabelionato_protestos',
                'category_label' => 'Tabelionato de Protestos',
                'sort_order' => 5,
                'show_in_quick_access' => true,
                'show_in_service_grid' => false,
                'is_active' => true,
            ],
            [
                'title' => 'Registro Civil de Pessoas Naturais',
                'label' => 'Registro Civil de Pessoas Naturais',
                'description' => 'Acesso aos serviços do Registro Civil de Pessoas Naturais.',
                'icon_url' => 'https://www.figma.com/api/mcp/asset/d0f50ac4-182b-48a0-9c00-7225cb762241.png',
                'href' => 'https://www.rtdbrasil.org.br/',
                'accent' => 'border-brand-green',
                'tag_text' => 'text-brand-green',
                'tag_bg' => 'bg-[#f7fbf4]',
                'category' => 'registro_civil',
                'category_label' => 'Registro Civil de Pessoas Naturais',
                'sort_order' => 10,
                'show_in_quick_access' => false,
                'show_in_service_grid' => true,
                'is_active' => true,
            ],
            [
                'title' => 'Registro de Imóveis',
                'label' => 'Registro de Imóveis',
                'description' => 'Consulta e gestão de registros e documentos do setor imobiliário.',
                'icon_url' => 'https://www.figma.com/api/mcp/asset/7187cb99-bbc3-488a-af5a-25a4eb969c20.png',
                'href' => 'https://registradores.onr.org.br/servicos/actitulo/frmAcompanhamentoTitulo.aspx',
                'accent' => 'border-brand-orange',
                'tag_text' => 'text-brand-orange',
                'tag_bg' => 'bg-[#fff8f3]',
                'category' => 'registro_imoveis',
                'category_label' => 'Registro de Imóveis',
                'sort_order' => 20,
                'show_in_quick_access' => false,
                'show_in_service_grid' => true,
                'is_active' => true,
            ],
            [
                'title' => 'Registro de Títulos e Documentos',
                'label' => 'Registro de Títulos e Documentos',
                'description' => 'Central de acesso para títulos, documentos e atos registráveis.',
                'icon_url' => 'https://www.figma.com/api/mcp/asset/973c87d4-0fa5-4583-a13c-19dd9c710364.png',
                'href' => 'https://www.rtdbrasil.org.br/coletaassinatura/assinardocumento',
                'accent' => 'border-brand-purple',
                'tag_text' => 'text-brand-purple',
                'tag_bg' => 'bg-[#f7f5ff]',
                'category' => 'titulos_documentos',
                'category_label' => 'Registro de Títulos e Documentos',
                'sort_order' => 30,
                'show_in_quick_access' => false,
                'show_in_service_grid' => true,
                'is_active' => true,
            ],
            [
                'title' => 'Tabelionato de Notas',
                'label' => 'Tabelionato de Notas',
                'description' => 'Acesso aos serviços de autenticação, atos e registros notariais.',
                'icon_url' => 'https://www.figma.com/api/mcp/asset/ab40a91d-80b8-450d-bc75-2933aa830784.png',
                'href' => 'https://www.e-notariado.org.br/customer/certificate-request',
                'accent' => 'border-brand-teal',
                'tag_text' => 'text-brand-teal',
                'tag_bg' => 'bg-[#f2fcfd]',
                'category' => 'tabelionato_notas',
                'category_label' => 'Tabelionato de Notas',
                'sort_order' => 40,
                'show_in_quick_access' => false,
                'show_in_service_grid' => true,
                'is_active' => true,
            ],
            [
                'title' => 'Tabelionato de Protestos',
                'label' => 'Tabelionato de Protestos',
                'description' => 'Acesso aos serviços de consulta e registro de protestos.',
                'icon_url' => 'https://www.figma.com/api/mcp/asset/1ee44ae4-3ac1-41f7-8755-0634bde282c9.png',
                'href' => 'https://www.pesquisaprotesto.com.br/servico/consulta-documento',
                'accent' => 'border-brand-blue',
                'tag_text' => 'text-brand-blue',
                'tag_bg' => 'bg-[#f3f9ff]',
                'category' => 'tabelionato_protestos',
                'category_label' => 'Tabelionato de Protestos',
                'sort_order' => 50,
                'show_in_quick_access' => false,
                'show_in_service_grid' => true,
                'is_active' => true,
            ],
            [
                'title' => 'Cartórios de Registro e Notas',
                'label' => 'Cartórios de Registro e Notas',
                'description' => 'Acesso aos serviços vinculados aos cartórios de registro e notas.',
                'icon_url' => 'https://www.figma.com/api/mcp/asset/9bad48fe-e164-4ba2-9dc7-a25c03e73fb4.png',
                'href' => '#',
                'accent' => 'border-brand-line',
                'tag_text' => 'text-brand-navy',
                'tag_bg' => 'bg-white',
                'category' => 'cartorios_registro_notas',
                'category_label' => 'Cartórios de Registro e Notas',
                'sort_order' => 60,
                'show_in_quick_access' => false,
                'show_in_service_grid' => true,
                'is_active' => true,
            ],
        ];

        foreach ($cards as $card) {
            Card::query()->updateOrCreate(
                ['title' => $card['title']],
                $card,
            );
        }
    }
}
